export const geography_options = [ 
	{ value:'blocks', label: 'Blocks', labelPR: 'Blocos'},
	{ value:'districts', label: 'Districts', labelPR: 'Distritos'},
];

export const district_metrics = [
	{category:"Social", palette:'sequ', max:'75', min:'20', breaks:'20,39.483,44.511,49.54', value:'AGE', legend:'none', label:'Age', labelPR:'Idade'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.465,0.704,0.942', value:'GEN_F', legend:'gender', label:'Gender', labelPR:'Genero'},
	{category:"Social", palette:'sequ', max:'55', min:'0', breaks:'0,0.1,17.123,34.389', value:'NUM_YR_SP', legend:'none', label:'Years in São Paulo', labelPR:'Duração de tempo em Sao Paulo'},
	{category:"Social", palette:'sequ', max:'20', min:'0', breaks:'0,4.242,10.082,15.922', value:'NUM_YR_HSE', legend:'none', label:'Years in Current Dwelling', labelPR:'Duração de tempo na casa atual'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.16,0.344,0.528', value:'BRTH_SP', legend:'secureA', label:'Native Paulista', labelPR:'Paulistano/a'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.498,0.79,0.81', value:'BRTH_REG_NE', legend:'secureA', label:'Non Native Paulista - North-East', labelPR:'NÃO Paulistano/a Paulista - Norte e Nordeste'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.05,0.112,0.258', value:'BRTH_REG_S', legend:'secureA', label:'Non Native Paulista - South-Central', labelPR:'NÃO Paulistano/a -  Sul e Centro'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.05,0.292,0.586', value:'DISP_Y', legend:'secureA', label:'Displacement', labelPR:'Remoção'},
	{category:"Social", palette:'sequ', max:'5.5', min:'0', breaks:'0,0.1,1.281,2.61', value:'NUM_FAM_LOT', legend:'none', label:'Lot Occupation', labelPR:'Ocupação'},
	{category:"Social", palette:'sequ', max:'5', min:'0', breaks:'0,2.23,3.431,4.633', value:'NUM_PPL_HSHD', legend:'none', label:'Household Inhabitants', labelPR:'Habitantes domésticos'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.1,0.107,0.231', value:'ED_LVL_0', legend:'secureA', label:'Respondent Education - None', labelPR:'Nível educacional do entrevistado - Nada'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.213,0.43,0.648', value:'ED_LVL_1', legend:'secureA', label:'Respondent Education - Elementary', labelPR:'Nível educacional do entrevistado - primária'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.157,0.361,0.566', value:'ED_LVL_2', legend:'secureA', label:'Respondent Education - High School', labelPR:'Nível educacional do entrevistado - ensino médio'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.01,0.091,0.198', value:'ED_LVL_3', legend:'secureA', label:'Respondent Education - Undergraduate Deg.', labelPR:'Nível educacional do entrevistado - Graduação'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.276,0.523,0.769', value:'ED_LVL_MOT_0', legend:'secureA', label: "Respondent Mother's Education - None", labelPR:'Nível educacional do mãe de entrevistado - Nada'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.091,0.307,0.522', value:'ED_LVL_MOT_1', legend:'secureA', label: "Respondent Mother's Education - Elementary", labelPR:'Nível educacional do mãe de entrevistado - primária'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.01,0.052,0.138', value:'ED_LVL_MOT_2', legend:'secureA', label: "Respondent Mother's Education - High School", labelPR:'Nível educacional do mãe de entrevistado - High'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.01,0.012,0.048', value:'ED_LVL_MOT_3', legend:'secureA', label: "Respondent Mother's Education - Undergraduate Deg.", labelPR:'Nível educacional do mãe de entrevistado - Graduação'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.01,0.099,0.301', value:'ED_LVL_MOT_5', legend:'secureA', label: "Respondent Mother's Education - No Information", labelPR:'Nível educacional do mãe de entrevistado - sem informação'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.23,0.456,0.682', value:'ED_LVL_FAT_0', legend:'secureA', label: "Respondent Father's Education - None", labelPR:'Nível educacional do pai de entrevistado - Nada'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.048,0.273,0.499', value:'ED_LVL_FAT_1', legend:'secureA', label: "Respondent Father's Education - Elementary", labelPR:'Nível educacional do pai de entrevistado - primária'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.01,0.056,0.144', value:'ED_LVL_FAT_2', legend:'secureA', label: "Respondent Father's Education - High School", labelPR:'Nível educacional do pai de entrevistado - High'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.01,0.017,0.061', value:'ED_LVL_FAT_3', legend:'secureA', label: "Respondent Father's Education - Undergraduate Deg.", labelPR:'Nível educacional do pai de entrevistado - Graduação'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0,0.003,0.004', value:'ED_LVL_FAT_4', legend:'secureA', label: "Respondent Father's Education - Graduate Deg.", labelPR:'Nível educacional do pai de entrevistado - Graduate Deg.'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.09,0.19,0.405', value:'ED_LVL_FAT_5', legend:'secureA', label: "Respondent Father's Education - No Information", labelPR:'Nível educacional do pai de entrevistado - sem informação'},
	{category:"Social", palette:'sequ', max:'2.1', min:'0', breaks:'0,0.048,0.889,1.73', value:'NUM_SCH_AGE_CHD', legend:'none', label:'School Age Children', labelPR:'Idade Escolar'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.224,0.445,0.666', value:'EMPL_Y', legend:'secureA', label:'Employment', labelPR:'Emprego'},
	{category:"Social", palette:'sequ', max:'2655', min:'0', breaks:'0,812.878,1525.882,2238.887', value:'INCOME', legend:'none', label:'Income', labelPR:'Renda'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.046,0.211,0.376', value:'USE_HM_INCM', legend:'secureA', label:'Home Income Generation', labelPR:'Necessidades especiais'},
	{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.001,0.089,0.189', value:'SPCL_NEEDS', legend:'secureA', label:'Special Needs', labelPR:'Geração de renda doméstica'},
	
	{category:"Physical", palette:'sequ', max:'8', min:'1', breaks:'1,2.101,2.876,3.651', value:'NUM_FLR', legend:'none', label:'Building Height', labelPR:'Pavimentos'},
	{category:"Physical", palette:'sequ', max:'1', min:'0', breaks:'0,0.373,0.652,0.931', value:'RENOV', legend:'secureA', label:'Home Expansion', labelPR:'Expansão domiciliar'},
	{category:"Physical", palette:'sequ', max:'4', min:'0', breaks:'0,1.967,3.012,3.5', value:'BLDG_QLTY', legend:'none', label:'Building Quality and Physical Consolidation', labelPR:'Qualidade de construção e consolidação física'},
	
	{category:"Urban Livability", palette:'sequ', max:'1', min:'0', breaks:'0,0.381,0.681,0.981', value:'SNS_SEC_HSE', legend:'secureA', label:'Sense of Security at Home', labelPR:'Sentido de segurança em casa'},
	{category:"Urban Livability", palette:'sequ', max:'1', min:'0', breaks:'0,0.105,0.441,0.776', value:'SNS_SEC_NEI', legend:'secureA', label:'Sense of Security on the Street', labelPR:'Sentido de segurança na rua'},
	{category:"Urban Livability", palette:'sequ', max:'1', min:'0', breaks:'0,0.009,0.422,0.834', value:'SNS_GOOD_ACS', legend:'secureA', label:'Sense of Access to Public Services', labelPR:'Sentido de acesso aos serviços públicos'},
	{category:"Urban Livability", palette:'sequ', max:'1', min:'0', breaks:'0,0.1,0.137,0.33', value:'ACS_LDR', legend:'secureA', label:'Sense of Access to Community Leader', labelPR:'Sentido de acesso a um líder da comunidade'},
	{category:"Urban Livability", palette:'sequ', max:'11', min:'0', breaks:'0,0.1,2.576,5.738', value:'LIXO_IMM_VIC', legend:'none', label:'Everyday challenge – Trash', labelPR:'Desafio maior - lixo'},
	{category:"Urban Livability", palette:'sequ', max:'17', min:'0', breaks:'0,1,2.939,7.092', value:'DROGA_IMM_VIC', legend:'none', label:'Everyday challenge – Drugs', labelPR:'Desafio maior – trafico de droga'},
	{category:"Urban Livability", palette:'sequ', max:'39', min:'0', breaks:'0,1,10.061,23.036', value:'BARULHO_IMM_VIC', legend:'none', label:'Everyday challenge – Noise Pollution', labelPR:'Desafio maior – barulho'},
	{category:"Urban Livability", palette:'sequ', max:'36', min:'0', breaks:'0,1,8.394,20.023', value:'NADA_IMM_VIC', legend:'none', label:'Everyday challenge – Nothing', labelPR:'Desafio maior – Nada'},
	{category:"Urban Livability", palette:'sequ', max:'4', min:'0', breaks:'0,1,1.152,2.568', value:'ASSAULTO_IMM_VIC', legend:'none', label:'Everyday challenge – Street Assault', labelPR:'Desafio maior – assalto'},
	{category:"Urban Livability", palette:'sequ', max:'5', min:'0', breaks:'0,1,2,3', value:'FUNK_IMM_VIC', legend:'none', label:'Everyday challenge – Funk Street Parties', labelPR:'Desafio maior – Baile Funk'},
	{category:"Urban Livability", palette:'sequ', max:'0.8', min:'0', breaks:'0,0.208,0.457,0.705', value:'CUR_INTENT', legend:'none', label:'Intention', labelPR:'Planos de futuro'},
	{category:"Urban Livability", palette:'sequ', max:'1', min:'0', breaks:'0,0.1,0.086,0.207', value:'POL_AFL', legend:'secureA', label:'Political Affiliation', labelPR:'Afiliação política'},
	{category:"Urban Livability", palette:'sequ', max:'4', min:'0', breaks:'0,0.755,2.142,3.529', value:'POL_PRIOR_INFRA', legend:'none', label:'Critical Change - Infrastructure and Sanitation', labelPR:'Mudança importante - Infraestrutura e saneamento'},
	{category:"Urban Livability", palette:'sequ', max:'4.3', min:'0', breaks:'0,0.882,2.401,3.92', value:'POL_PRIOR_WST_MGT', legend:'none', label:'Critical Change - Waste Management', labelPR:'Mudança importante – Coleção de lixo'},
	{category:"Urban Livability", palette:'sequ', max:'3.6', min:'0', breaks:'0,0.669,2.02,3.371', value:'POL_PRIOR_ENV', legend:'none', label:'Critical Change - Environmental Stewardship', labelPR:'Mudança importante – Meio ambient'},
	{category:"Urban Livability", palette:'sequ', max:'4.1', min:'0', breaks:'0,0.774,2.303,3.832', value:'POL_PRIOR_HSG', legend:'none', label:'Critical Change - Housing', labelPR:'Mudança importante – Habitação'},
	{category:"Urban Livability", palette:'sequ', max:'4', min:'0', breaks:'0,0.579,1.97,3.36', value:'POL_PRIOR_TTL', legend:'none', label:'Critical Change - Title', labelPR:'Mudança importante – Regularização'}
];

export const blocks_metrics = [
		{category:"Social", palette:'sequ', max:'75', min:'20', breaks:'20,36.387,44.594,52.801', value:'AGE', legend:'none', label:'Age', labelPR:'Idade'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.445,0.707,0.969', value:'GEN_F', legend:'gender', label:'Gender', labelPR:'Genero'},
		{category:"Social", palette:'sequ', max:'55', min:'0', breaks:'0,1.883,18.375,34.867', value:'NUM_YR_SP', legend:'none', label:'Years in São Paulo', labelPR:'Duração de tempo em Sao Paulo'},
		{category:"Social", palette:'sequ', max:'32', min:'0', breaks:'0,5.491,12.48,19.468', value:'NUM_YR_HSE', legend:'none', label:'Years in Current Dwelling', labelPR:'Duração de tempo na casa atual'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.07,0.333,0.596', value:'BRTH_SP', legend:'secureA', label:'Native Paulista', labelPR:'Paulistano/a'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.541,0.81,0.9', value:'BRTH_REG_NE', legend:'secureA', label:'Non Native Paulista - North-East', labelPR:'NÃO Paulistano/a Paulista - Norte e Nordeste'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.1,0.139,0.344', value:'BRTH_REG_S', legend:'secureA', label:'Non Native Paulista - South-Central', labelPR:'NÃO Paulistano/a -  Sul e Centro'},

		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.1,0.234,0.545', value:'DISP_Y', legend:'secureA', label:'Displacement', labelPR:'Remoção'},
		{category:"Social", palette:'sequ', max:'14.6', min:'0', breaks:'0,0.1,1.421,2.981', value:'NUM_FAM_LOT', legend:'none', label:'Lot Occupation', labelPR:'Ocupação'},
		{category:"Social", palette:'sequ', max:'7.5', min:'0', breaks:'0,2.344,3.557,4.77', value:'NUM_PPL_HSHD', legend:'none', label:'Household Inhabitants', labelPR:'Habitantes domésticos'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.01,0.1,0.287', value:'ED_LVL_0', legend:'secureA', label:'Respondent Education - None', labelPR:'Nível educacional do entrevistado - Nada'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.151,0.427,0.703', value:'ED_LVL_1', legend:'secureA', label: "Respondent Education - Elementary", labelPR:'Nível educacional do entrevistado - primária'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.098,0.352,0.606', value:'ED_LVL_2', legend:'secureA', label: "Respondent Education - High School", labelPR:'Nível educacional do entrevistado - ensino médio'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.01,0.106,0.275', value:'ED_LVL_3', legend:'secureA', label: "Respondent Education - Undergraduate Deg.", labelPR:'Nível educacional do entrevistado - Graduação'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.236,0.522,0.808', value:'ED_LVL_MOT_0', legend:'secureA', label: "Respondent Mother's Education - None", labelPR:'Nível educacional do mãe de entrevistado - Nada'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.062,0.331,0.599', value:'ED_LVL_MOT_1', legend:'secureA', label: "Respondent Mother's Education - Elementary", labelPR:'Nível educacional do mãe de entrevistado - primária'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.001,0.05,0.175', value:'ED_LVL_MOT_2', legend:'secureA', label: "Respondent Mother's Education - High", labelPR:'Nível educacional do mãe de entrevistado - High'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.001,0.014,0.101', value:'ED_LVL_MOT_3', legend:'secureA', label: "Respondent Mother's Education - Undergraduate Deg.", labelPR:'Nível educacional do mãe de entrevistado - Graduação'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.01,0.07,0.24', value:'ED_LVL_MOT_5', legend:'secureA', label: "Respondent Mother's Education - No Information", labelPR:'Nível educacional do mãe de entrevistado - sem informação'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.178,0.469,0.76', value:'ED_LVL_FAT_0', legend:'secureA', label: "Respondent Father's Education - None", labelPR:'Nível educacional do pai de entrevistado - Nada'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.028,0.286,0.544', value:'ED_LVL_FAT_1', legend:'secureA', label: "Respondent Father's Education - Elementary", labelPR:'Nível educacional do pai de entrevistado - primária'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.01,0.05,0.169', value:'ED_LVL_FAT_2', legend:'secureA', label: "Respondent Father's Education - High", labelPR:'Nível educacional do pai de entrevistado - High'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.001,0.013,0.075', value:'ED_LVL_FAT_3', legend:'secureA', label: "Respondent Father's Education - Undergraduate Deg.", labelPR:'Nível educacional do pai de entrevistado - Graduação'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0,0.002,0.016', value:'ED_LVL_FAT_4', legend:'secureA', label: "Respondent Father's Education - Graduate Deg.", labelPR:'Nível educacional do pai de entrevistado - Graduate Deg.'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.1,0.168,0.411', value:'ED_LVL_FAT_5', legend:'secureA', label: "Respondent Father's Education - No Information", labelPR:'Nível educacional do pai de entrevistado - sem informação'},
		{category:"Social", palette:'sequ', max:'4', min:'0', breaks:'0,0.224,1.12,2.016', value:'NUM_SCH_AG', legend:'none', label:'School Age Children', labelPR:'Idade Escolar'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.19,0.476,0.761', value:'EMPL_Y', legend:'secureA', label:'Employment', labelPR:'Emprego'},
		{category:"Social", palette:'sequ', max:'7640', min:'0', breaks:'0,857.928,1743.932,2629.936', value:'INCOME', legend:'none', label:'Income', labelPR:'Renda'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.1,0.094,0.237', value:'SPCL_NEEDS', legend:'secureA', label:'Special Needs', labelPR:'Necessidades especiais'},
		{category:"Social", palette:'sequ', max:'1', min:'0', breaks:'0,0.1,0.221,0.459', value:'USE_HM_INCM', legend:'secureA', label:'Home Income Generation', labelPR:'Geração de renda doméstica'},

		{category:"Physical", palette:'sequ', max:'8', min:'1', breaks:'1,1.774,2.656,3.537', value:'NUM_FLR', legend:'none', label:'Building Height', labelPR:'Pavimentos'},
		{category:"Physical", palette:'sequ', max:'1', min:'0', breaks:'0,0.434,0.723,1.011', value:'RENOV', legend:'secureA', label:'Home Expansion', labelPR:'Expansão domiciliar'},
		{category:"Physical", palette:'sequ', max:'5', min:'0', breaks:'0,2.307,3.139,3.972', value:'BLDG_QLTY', legend:'none', label:'Building Quality and Physical Consolidation', labelPR:'Qualidade de construção e consolidação física'},

		{category:"Urban Livability", palette:'sequ', max:'1', min:'0', breaks:'0,0.41,0.719,1.029', legend:'secureA', value:'SNS_SEC_HSE', label:'Sense of Security at Home', labelPR:'Sentido de segurança em casa'},
		{category:"Urban Livability", palette:'sequ', max:'1', min:'0', breaks:'0,0.203,0.562,0.922', legend:'secureA', value:'SNS_SEC_NE', label:'Sense of Security on the Street', labelPR:'Sentido de segurança na rua'},
		{category:"Urban Livability", palette:'sequ', max:'1', min:'0', breaks:'0,0.124,0.541,0.958', legend:'secureA', value:'SNS_GOOD_ACS', label:'Sense of Access to Public Services', labelPR:'Sentido de acesso aos serviços públicos'},
		{category:"Urban Livability", palette:'sequ', max:'1', min:'0', breaks:'0,0.1,0.205,0.489', legend:'secureA', value:'ACS_LDR', label:'Sense of Access to Community Leader', labelPR:'Sentido de acesso a um líder da comunidade'},
		{category:"Urban Livability", palette:'sequ', max:'4', min:'0', breaks:'0,1,2,3', legend:'none', value:'LIXO_IMM_VIC', label:'Everyday challenge – Trash', labelPR:'Desafio maior - lixo'},
		{category:"Urban Livability", palette:'sequ', max:'5', min:'0', breaks:'0,1,2,3', legend:'none', value:'DROGA_IMM_VIC', label:'Everyday challenge – Drugs', labelPR:'Desafio maior – trafico de droga'},
		{category:"Urban Livability", palette:'sequ', max:'8', min:'0', breaks:'0,2,4,6', legend:'none', value:'BARULHO_IMM_VIC', label:'Everyday challenge – Noise Pollution', labelPR:'Desafio maior – barulho'},
		{category:"Urban Livability", palette:'sequ', max:'7', min:'0', breaks:'0,2,4,6', legend:'none', value:'NADA_IMM_V', label:'Everyday challenge – Nothing', labelPR:'Desafio maior – Nada'},
		{category:"Urban Livability", palette:'sequ', max:'3', min:'0', breaks:'0,0.9,1.9,2.9', legend:'none', value:'ASSAULTO_IMM_VIC', label:'Everyday challenge – Street Assault', labelPR:'Desafio maior – assalto'},
		{category:"Urban Livability", palette:'sequ', max:'4', min:'0', breaks:'0,1,2,3', legend:'none', value:'FUNK_IMM_VIC', label:'Everyday challenge – Funk Street Parties', labelPR:'Desafio maior – Baile Funk'},
		{category:"Urban Livability", palette:'sequ', max:'1', min:'0', breaks:'0,0.01,0.097,0.273', legend:'none', value:'POL_AFL', label:'Political Affiliation', labelPR:'Planos de futuro'},
		{category:"Urban Livability", palette:'sequ', max:'1', min:'0', breaks:'0,0.239,0.535,0.831', legend:'secureA', value:'CUR_INTENT', label:'Intention', labelPR:'Afiliação política'},
		{category:"Urban Livability", palette:'sequ', max:'5', min:'0', breaks:'0,0.638,1.921,3.203', legend:'none', value:'POL_PRIOR_TTL', label:'Critical Change - Title', labelPR:'Mudança importante - Infraestrutura e saneamento'},
		{category:"Urban Livability", palette:'sequ', max:'5', min:'0', breaks:'0,0.813,2.175,3.537', legend:'none', value:'POL_PRIOR_INFRA', label:'Critical Change - Infrastructure and Sanitation', labelPR:'Mudança importante – Coleção de lixo'},
		{category:"Urban Livability", palette:'sequ', max:'5', min:'0', breaks:'0,1.023,2.552,4.08', legend:'none', value:'POL_PRIOR_WST_MGT', label:'Critical Change - Waste Management', labelPR:'Mudança importante – Meio ambient'},
		{category:"Urban Livability", palette:'sequ', max:'5', min:'0', breaks:'0,0.886,2.279,3.672', legend:'none', value:'POL_PRIOR_ENV', label:'Critical Change - Environmental Stewardship', labelPR:'Mudança importante – Habitação'},
		{category:"Urban Livability", palette:'sequ', max:'5', min:'0', breaks:'0,0.918,2.492,4.066', legend:'none', value:'POL_PRIOR_HSG', label:'Critical Change - Housing', labelPR:'Mudança importante – Regularização'}

];